-- AlterTable
ALTER TABLE "projects" ADD COLUMN     "cpu" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "memory" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "storage" DOUBLE PRECISION NOT NULL DEFAULT 0;
